export const category = [
  { name: 'Diabetes' },
  { name: 'Cancer' },
  { name: 'Cardiovascular' },
  { name: 'Alzheimer' },
  { name: 'Hypertension' },
  { name: 'Obesity' },
  { name: 'Old Age' },
  { name: 'Infection' },
  { name: 'Cerebral palsy' },
  { name: 'Mental Disorder' },
  { name: 'Schizophrenia' },
  { name: 'Autism' },
  { name: 'Depression' },
  { name: 'HIV' },
  { name: 'Hemorrhage' },
  { name: 'Stroke' },
  { name: 'Heart Attack' },
  { name: 'Asthma' },
  { name: 'Respiratory Infection' },
  { name: 'Transplant' },
  { name: 'Tumomur' },
  { name: 'Kidney' },
  { name: 'Brain' },
  { name: 'Addiction' },
  { name: 'Stroke' },
  { name: 'Operation' },
  { name: 'Medicine' },
  { name: 'Treatment' },
  { name: 'Dementia' },
  { name: 'Pneumonia' },
];

export const countriesList = [
  'India',
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'New Zealand',
  'Germany',
  'France',
  'Japan',
  'China',
  'South Korea',
  'Brazil',
  'Argentina',
  'Mexico',
  'Spain',
  'Switzerland',
  'Italy',
  'Netherlands',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Belgium',
  'Austria',
  'Portugal',
  'Ireland',
  'Russia',
  'Poland',
  'Romania',
  'Greece',
  'Turkey',
];
